default_config:

logger:
#  default: info
  default: warning
  logs:
    custom_components.volkswagen_we_connect_id: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy: